# it's api
apiVersion: apps/v1
# it's object type
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  # by this we trace pod creation in master
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000
